name: Secret Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Secret (API_KEY)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Secret is being used safely"
          echo "API call simulation done"
