name: CI Workflow

on:
  push:
    branches: [main]
    
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - run: pip install -r requirements.txt
      - run: pytest


  api_auth:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" https://api.example.com


  database:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "DB Password: ${{ secrets.DB_PASSWORD }}"


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying app"
